site_name: Fiddler
site_url: https://rc1405.github.io/fiddler
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Configuration: configuration.md
theme: 
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  palette:
    scheme: slate
    primary: light green
extra:
  version:
    provider: mike

plugins:
  - search
  - mike:
      version_selector: true
hooks:
  - hooks.py