site_name: Fiddler
site_url: https://rc1405.github.io/fiddler
repo_url: https://github.com/rc1405/fiddler
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Configuration: configuration.md
theme: 
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: light green
extra:
  version:
    provider: mike

plugins:
  - search
  - mike:
      version_selector: true
hooks:
  - hooks.py

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true