name: safety
permissions:
  contents: read
on:
  pull_request:
    paths-ignore:
      - 'fiddler-cli/**'
      - 'fiddler/**'
      - 'Cargo.toml'
jobs:
  # https://twitter.com/mycoliza/status/1571295690063753218
  nightly:
    runs-on: ubuntu-latest
    name: ubuntu / nightly
    steps:
      - name: stable / fmt
        run: echo pass
      - name: ubuntu / stable / features
        run: echo pass
      - name: macos-13 / stable
        run: echo pass
      - name: stable / clippy
        run: echo pass