name: release
permissions:
  pull-requests: write
  contents: write
  actions: write
  pages: write
on:
  push:
    branches:
      - main
env:
  BIN_NAME: fiddler-cli

jobs:
  release-plz-release:
    name: release
    runs-on: ubuntu-latest
    environment: prd
    permissions:
      contents: write
    outputs:
      releases: ${{ steps.release-plz.outputs.releases }}
      version: ${{ steps.normalized_version.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        id: release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
      - name: normalized_version
        if: ${{ steps.release-plz-release.outputs.releases[0] }}
        run: |
          version=$(echo ${{ steps.release-plz.outputs.releases }} |jq -r '.releases[] | select(.package_name == "fiddler")|.version')
          echo "version=$version" >> $GITHUB_OUTPUT
  release-website:
    name: generate website
    needs: release-plz-release
    if: ${{ fromJson(needs.release-plz-release.outputs.releases)[0] }}
    uses: ./.github/workflows/website.yml
    with:
      version: ${{ needs.release-plz-release.outputs.version }}
  release-binaries:
    name: generate binaries
    needs: release-plz-release
    if: ${{ fromJson(needs.release-plz-release.outputs.releases)[0] }}
    uses: ./.github/workflows/assets.yml
    with:
      version: ${{ needs.release-plz-release.outputs.version }}

  release-plz-pr:
    name: pr
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
