name: upload website

permissions:
  contents: write
  pages: write

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        type: string
defaults:
  run:
    shell: bash

jobs:
  generate_website:
    name: generate website
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: fiddler-cli-v${{ inputs.version }}
      - run: git fetch origin gh-pages --depth=1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
        working-directory: website/
      - run: |
          mike deploy -p ${{ inputs.version }}
          mike alias ${{ inputs.version }} latest -p -u
        if: ${{ github.event_name == 'workflow_dispatch' }}
        working-directory: website/
        env:
          GIT_COMMITTER_NAME: ci-bot 
          GIT_COMMITTER_EMAIL: ci-bot@fiddler-rs.dev 
      - run: |
          mike deploy -p $(echo $FIDDLER_VERSION|sed 's/fiddler-cli-v//g')
          mike alias $(echo $FIDDLER_VERSION|sed 's/fiddler-cli-v//g') latest -p -u
        if: ${{ github.event_name != 'workflow_dispatch' }}
        env:
            FIDDLER_VERSION: ${{ github.event.release.name }}
        working-directory: website/