name: upload website

permissions:
  contents: write
  pages: write

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
  push:
    tags:
      - fiddler-cli-v**

defaults:
  run:
    shell: bash

jobs:
  generate_website:
    name: generate website
    if: github.repository_owner == 'rc1405' && (startsWith(github.event.release.name, 'fiddler-cli-v') || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
        working-directory: website/
      - run: mike deploy ${{ inputs.version }}
        if: ${{ github.event_name == 'workflow_dispatch' }}
        working-directory: website/
      - run: mike deploy $(echo $FIDDLER_VERSION|sed 's/fiddler-cli-v//g')
        if: ${{ github.event_name != 'workflow_dispatch' }}
        env:
            FIDDLER_VERSION: ${{ github.event.release.name }}
        working-directory: website/